name: Android CI

on: [ push ]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      CenterStage_changed: ${{ steps.filter.outputs.CenterStage_changed }}
      api_changed: ${{ steps.filter.outputs.api_changed }}
      mpc_changed: ${{ steps.filter.outputs.mpc_changed }}
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            CenterStage_changed:
              - 'CenterStage/**'
            api_changed:
               - 'api/**'
            mpc_changed:
                - 'mpc/**'

  build_CenterStage:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.CenterStage_changed == 'true' }}
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: CenterStage build and test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: :CenterStage:test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "CenterStage/build/test-results/**/*.xml"

  build_api:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.api_changed == 'true' }}
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: api build and test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: :api:test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "api/build/test-results/**/*.xml"

  build_mpc:
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.mpc_changed == 'true' }}
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: mpc build and test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: :mpc:test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "mpc/build/test-results/**/*.xml"